# Development overrides for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      # Mount entire backend directory for hot reloading
      - ./backend:/app
      # Mount data directory for SQLite database (shared with host for persistence)
      - ./data:/app/data
    environment:
      - DEBUG=true
      - LOG_LEVEL=debug
      - PYTHONUNBUFFERED=1
      - WATCHFILES_FORCE_POLLING=true
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app
    # Compose v2.22+: Rebuild when dependencies change
    develop:
      watch:
        - action: rebuild
          path: ./backend/requirements.txt

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development # Use development stage with source code
    restart: "no"
    # Bind mount source for hot reload; keep node_modules and .next as container volumes
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - CI=true
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000
      # Ensure file watching works on Docker Desktop (macOS/Windows)
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NEXT_TELEMETRY_DISABLED=1
    command: sh -c "[ -d node_modules ] || pnpm install --frozen-lockfile; pnpm exec next dev -H 0.0.0.0 -p 3000"
    healthcheck:
      disable: true
    # Compose v2.22+: Rebuild when dependencies change
    develop:
      watch:
        - action: rebuild
          path: ./frontend/package.json
        - action: rebuild
          path: ./frontend/pnpm-lock.yaml

# No additional services needed in development - using SQLite for schema storage
