openapi: 3.0.3
info:
  title: Schema Generator Service
  description: Service for generating document schemas from AI analysis results
  version: 1.0.0

paths:
  /generate_schema:
    post:
      summary: Generate schema from AI analysis result
      description: Creates a complete document schema based on AI analysis results and extracted fields
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                analysis_result_id:
                  type: string
                  description: Reference to AI analysis result
                generation_options:
                  type: object
                  properties:
                    confidence_threshold:
                      type: number
                      minimum: 0.0
                      maximum: 1.0
                      default: 0.6
                      description: Minimum confidence for auto-inclusion
                    include_low_confidence:
                      type: boolean
                      default: true
                      description: Include low-confidence fields for review
                    generate_validation_rules:
                      type: boolean
                      default: true
                    schema_name_override:
                      type: string
                      description: Override AI-suggested schema name
                    field_name_format:
                      type: string
                      enum: [snake_case, camelCase, original]
                      default: snake_case
              required:
                - analysis_result_id
      responses:
        '200':
          description: Schema generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  generated_schema:
                    $ref: '#/components/schemas/GeneratedSchema'
                  validation_summary:
                    $ref: '#/components/schemas/ValidationSummary'
        '400':
          description: Invalid analysis result or parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Analysis result not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /generate_schema/validation_rules:
    post:
      summary: Generate validation rules for specific fields
      description: Creates detailed validation rules based on field analysis and content patterns
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                field_ids:
                  type: array
                  items:
                    type: string
                  description: Fields to generate validation rules for
                rule_types:
                  type: array
                  items:
                    type: string
                    enum: [pattern, length, range, format, custom]
                  description: Types of validation rules to generate
                strictness_level:
                  type: string
                  enum: [lenient, moderate, strict]
                  default: moderate
              required:
                - field_ids
      responses:
        '200':
          description: Validation rules generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  validation_rules:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        $ref: '#/components/schemas/ValidationRule'

  /generate_schema/preview:
    post:
      summary: Preview generated schema without saving
      description: Shows what the generated schema would look like without creating it
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                analysis_result_id:
                  type: string
                preview_options:
                  type: object
                  properties:
                    confidence_threshold:
                      type: number
                      minimum: 0.0
                      maximum: 1.0
                    include_statistics:
                      type: boolean
                      default: true
                    include_recommendations:
                      type: boolean
                      default: true
              required:
                - analysis_result_id
      responses:
        '200':
          description: Schema preview generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  schema_preview:
                    $ref: '#/components/schemas/SchemaPreview'
                  generation_statistics:
                    type: object
                    properties:
                      total_fields:
                        type: integer
                      high_confidence_fields:
                        type: integer
                      auto_included_fields:
                        type: integer
                      requires_review_fields:
                        type: integer
                  recommendations:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          enum: [field_modification, validation_rule, schema_structure]
                        description:
                          type: string
                        priority:
                          type: string
                          enum: [high, medium, low]

  /save_generated_schema:
    post:
      summary: Save generated schema to storage
      description: Persists generated schema using existing schema management system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                generated_schema:
                  $ref: '#/components/schemas/GeneratedSchema'
                save_options:
                  type: object
                  properties:
                    status:
                      type: string
                      enum: [draft, under_review, approved]
                      default: draft
                    open_in_editor:
                      type: boolean
                      default: true
                    notify_user:
                      type: boolean
                      default: true
              required:
                - generated_schema
      responses:
        '201':
          description: Schema saved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  schema_id:
                    type: string
                  edit_url:
                    type: string
                    description: URL to open schema in editor
                  storage_location:
                    type: string
        '400':
          description: Invalid schema data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Schema with same name already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    GeneratedSchema:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          description: Schema name (AI-generated or user-provided)
        description:
          type: string
        source_document_id:
          type: string
        analysis_result_id:
          type: string
        generation_metadata:
          type: object
          properties:
            generated_timestamp:
              type: string
              format: date-time
            ai_model_used:
              type: string
            generation_confidence:
              type: number
              minimum: 0.0
              maximum: 1.0
            generation_method:
              type: string
              enum: [ai_generated, ai_assisted]
        fields:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/GeneratedField'
        validation_rules:
          type: object
          additionalProperties:
            type: array
            items:
              $ref: '#/components/schemas/ValidationRule'
        quality_metrics:
          type: object
          properties:
            total_fields_generated:
              type: integer
            high_confidence_fields:
              type: integer
            auto_included_fields:
              type: integer
            requires_review_fields:
              type: integer
            overall_schema_confidence:
              type: number
              minimum: 0.0
              maximum: 1.0
        user_interaction:
          type: object
          properties:
            review_status:
              type: string
              enum: [pending, in_progress, reviewed, approved]
            requires_user_review:
              type: boolean
            suggested_modifications:
              type: array
              items:
                type: string
      required:
        - id
        - name
        - source_document_id
        - analysis_result_id
        - fields

    GeneratedField:
      type: object
      properties:
        display_name:
          type: string
        type:
          type: string
          enum: [string, number, date, boolean]
        required:
          type: boolean
        description:
          type: string
        examples:
          type: array
          items:
            type: string
        ai_metadata:
          type: object
          properties:
            source_field_id:
              type: string
              description: Reference to ExtractedField
            confidence_score:
              type: number
              minimum: 0.0
              maximum: 1.0
            extraction_method:
              type: string
            requires_review:
              type: boolean
            review_reason:
              type: string
            alternative_interpretations:
              type: array
              items:
                type: object
                properties:
                  field_name:
                    type: string
                  field_type:
                    type: string
                  confidence:
                    type: number
        validation_rules:
          type: array
          items:
            $ref: '#/components/schemas/ValidationRule'
      required:
        - display_name
        - type
        - required

    ValidationRule:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          enum: [pattern, length, range, format, custom]
        value:
          description: Rule parameter (varies by type)
        description:
          type: string
        confidence_score:
          type: number
          minimum: 0.0
          maximum: 1.0
        is_recommended:
          type: boolean
        priority:
          type: integer
          minimum: 1
          maximum: 10
        examples:
          type: object
          properties:
            valid_examples:
              type: array
              items:
                type: string
            invalid_examples:
              type: array
              items:
                type: string
        inference_metadata:
          type: object
          properties:
            inference_method:
              type: string
            sample_size:
              type: integer
            pattern_strength:
              type: number
              minimum: 0.0
              maximum: 1.0
      required:
        - id
        - type
        - value
        - description

    SchemaPreview:
      type: object
      properties:
        schema_name:
          type: string
        predicted_fields:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/GeneratedField'
        confidence_summary:
          type: object
          properties:
            overall_confidence:
              type: number
            field_confidence_distribution:
              type: object
              properties:
                high:
                  type: integer
                medium:
                  type: integer
                low:
                  type: integer
        quality_indicators:
          type: object
          properties:
            completeness_score:
              type: number
              description: How complete the schema appears
            consistency_score:
              type: number
              description: How consistent field types are
            validation_coverage:
              type: number
              description: Percentage of fields with validation rules
        preview_warnings:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                enum: [low_confidence, missing_validation, type_inconsistency]
              message:
                type: string
              field_name:
                type: string
              severity:
                type: string
                enum: [info, warning, error]

    ValidationSummary:
      type: object
      properties:
        total_validations:
          type: integer
        passed_validations:
          type: integer
        failed_validations:
          type: integer
        warnings:
          type: array
          items:
            type: object
            properties:
              field_name:
                type: string
              validation_type:
                type: string
              message:
                type: string
              severity:
                type: string
                enum: [info, warning, error]
        schema_compatibility:
          type: object
          properties:
            compatible_with_existing:
              type: boolean
            compatibility_issues:
              type: array
              items:
                type: string
            migration_required:
              type: boolean

    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object
        timestamp:
          type: string
          format: date-time
        request_id:
          type: string
      required:
        - error
        - message