openapi: 3.0.3
info:
  title: UI Integration API
  description: API for integrating AI schema generation with the existing schema management UI
  version: 1.0.0

paths:
  /ui/upload_sample_document:
    post:
      summary: Upload sample document for AI analysis
      description: Handles document upload through the UI with validation and preprocessing
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                document:
                  type: string
                  format: binary
                  description: Document file (PDF or image)
                filename:
                  type: string
                analysis_options:
                  type: string
                  description: JSON string of analysis options
                user_session_id:
                  type: string
              required:
                - document
                - filename
      responses:
        '200':
          description: Document uploaded and queued for analysis
          content:
            application/json:
              schema:
                type: object
                properties:
                  document_id:
                    type: string
                  upload_status:
                    type: string
                    enum: [uploaded, queued, processing]
                  analysis_eta:
                    type: integer
                    description: Estimated analysis time in seconds
                  progress_endpoint:
                    type: string
                    description: Endpoint to check analysis progress
        '400':
          description: Invalid file or parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '413':
          description: File too large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /ui/analysis_progress/{document_id}:
    get:
      summary: Check analysis progress
      description: Get real-time progress updates for document analysis
      parameters:
        - name: document_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Progress information
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [pending, analyzing, completed, failed]
                  progress_percentage:
                    type: integer
                    minimum: 0
                    maximum: 100
                  current_stage:
                    type: string
                    description: Current analysis stage
                  estimated_completion:
                    type: string
                    format: date-time
                  intermediate_results:
                    type: object
                    properties:
                      document_type_detected:
                        type: string
                      fields_detected_count:
                        type: integer
                      high_confidence_count:
                        type: integer
        '404':
          description: Document not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /ui/analysis_results/{document_id}:
    get:
      summary: Get complete analysis results
      description: Retrieve final analysis results when processing is complete
      parameters:
        - name: document_id
          in: path
          required: true
          schema:
            type: string
        - name: include_preview
          in: query
          schema:
            type: boolean
            default: false
          description: Include schema preview in response
      responses:
        '200':
          description: Analysis results available
          content:
            application/json:
              schema:
                type: object
                properties:
                  analysis_result:
                    $ref: '#/components/schemas/UIAnalysisResult'
                  schema_preview:
                    $ref: '#/components/schemas/UISchemaPreview'
                  ui_metadata:
                    type: object
                    properties:
                      recommended_next_action:
                        type: string
                        enum: [review_and_edit, accept_and_save, retry_analysis]
                      confidence_summary:
                        type: string
                        description: Human-readable confidence summary
                      review_priority_fields:
                        type: array
                        items:
                          type: string
                        description: Field names requiring attention
        '202':
          description: Analysis still in progress
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [processing]
                  progress:
                    type: integer

  /ui/transition_to_editor:
    post:
      summary: Transition to schema editor with AI-generated content
      description: Prepares schema management interface for editing AI-generated schema
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                document_id:
                  type: string
                schema_generation_options:
                  type: object
                  properties:
                    confidence_threshold:
                      type: number
                      minimum: 0.0
                      maximum: 1.0
                      default: 0.6
                    auto_accept_high_confidence:
                      type: boolean
                      default: true
                    open_mode:
                      type: string
                      enum: [edit, review, preview]
                      default: review
              required:
                - document_id
      responses:
        '200':
          description: Editor prepared successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  editor_session_id:
                    type: string
                  schema_data:
                    $ref: '#/components/schemas/UIEditableSchema'
                  editor_metadata:
                    type: object
                    properties:
                      mode:
                        type: string
                        enum: [edit_ai_generated, review_ai_generated]
                      confidence_indicators_enabled:
                        type: boolean
                      ai_suggestions_available:
                        type: boolean
                      source_document_reference:
                        type: string

  /ui/save_reviewed_schema:
    post:
      summary: Save schema after user review and editing
      description: Saves user-reviewed AI-generated schema to permanent storage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                editor_session_id:
                  type: string
                reviewed_schema:
                  $ref: '#/components/schemas/UIEditableSchema'
                user_modifications:
                  type: object
                  properties:
                    fields_modified:
                      type: array
                      items:
                        type: string
                    fields_added:
                      type: array
                      items:
                        type: string
                    fields_removed:
                      type: array
                      items:
                        type: string
                    validation_rules_modified:
                      type: boolean
                    schema_name_changed:
                      type: boolean
                save_options:
                  type: object
                  properties:
                    status:
                      type: string
                      enum: [draft, active]
                      default: draft
                    create_backup:
                      type: boolean
                      default: true
              required:
                - editor_session_id
                - reviewed_schema
      responses:
        '201':
          description: Schema saved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  schema_id:
                    type: string
                  save_status:
                    type: string
                    enum: [saved, saved_with_warnings]
                  warnings:
                    type: array
                    items:
                      type: string
                  next_steps:
                    type: array
                    items:
                      type: object
                      properties:
                        action:
                          type: string
                        description:
                          type: string
                        url:
                          type: string

  /ui/retry_analysis:
    post:
      summary: Retry analysis with different parameters
      description: Re-analyze document with user-adjusted parameters
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                document_id:
                  type: string
                retry_reason:
                  type: string
                  enum: [low_confidence, incorrect_fields, wrong_document_type, user_preference]
                retry_options:
                  type: object
                  properties:
                    different_model:
                      type: string
                      enum: [llama-scout, mistral-small]
                    adjusted_confidence_threshold:
                      type: number
                      minimum: 0.0
                      maximum: 1.0
                    focus_document_type:
                      type: string
                      description: Force specific document type classification
                    specific_field_hints:
                      type: array
                      items:
                        type: object
                        properties:
                          field_name:
                            type: string
                          expected_type:
                            type: string
                          location_hint:
                            type: string
              required:
                - document_id
                - retry_reason
      responses:
        '202':
          description: Retry analysis queued
          content:
            application/json:
              schema:
                type: object
                properties:
                  retry_id:
                    type: string
                  progress_endpoint:
                    type: string
                  estimated_completion:
                    type: string
                    format: date-time

components:
  schemas:
    UIAnalysisResult:
      type: object
      properties:
        document_info:
          type: object
          properties:
            filename:
              type: string
            file_type:
              type: string
            file_size:
              type: integer
            page_count:
              type: integer
        detection_results:
          type: object
          properties:
            document_type:
              type: string
            confidence:
              type: number
              minimum: 0.0
              maximum: 1.0
            confidence_description:
              type: string
              enum: [very_high, high, medium, low, very_low]
            alternative_types:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                  confidence:
                    type: number
                  reasoning:
                    type: string
        extracted_fields:
          type: array
          items:
            $ref: '#/components/schemas/UIExtractedField'
        analysis_summary:
          type: object
          properties:
            total_fields:
              type: integer
            high_confidence_fields:
              type: integer
            medium_confidence_fields:
              type: integer
            low_confidence_fields:
              type: integer
            requires_review_count:
              type: integer
            quality_score:
              type: number
              minimum: 0.0
              maximum: 1.0
        processing_metadata:
          type: object
          properties:
            model_used:
              type: string
            processing_time:
              type: number
            analysis_timestamp:
              type: string
              format: date-time

    UIExtractedField:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        display_name:
          type: string
        type:
          type: string
        value_example:
          type: string
        confidence:
          type: object
          properties:
            overall:
              type: number
              minimum: 0.0
              maximum: 1.0
            level:
              type: string
              enum: [high, medium, low]
            color:
              type: string
              enum: [green, orange, red]
            explanation:
              type: string
        location:
          type: object
          properties:
            page:
              type: integer
            description:
              type: string
            bounding_box:
              type: object
              nullable: true
        properties:
          type: object
          properties:
            is_required:
              type: boolean
            field_group:
              type: string
            has_validation_hints:
              type: boolean
        review_status:
          type: object
          properties:
            needs_review:
              type: boolean
            review_reason:
              type: string
            suggested_action:
              type: string
              enum: [accept, modify, remove, verify]
        alternatives:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              type:
                type: string
              confidence:
                type: number

    UISchemaPreview:
      type: object
      properties:
        schema_name:
          type: string
        schema_description:
          type: string
        field_summary:
          type: object
          properties:
            total_fields:
              type: integer
            auto_included:
              type: integer
            requires_review:
              type: integer
            will_be_excluded:
              type: integer
        confidence_overview:
          type: object
          properties:
            overall_confidence:
              type: number
            confidence_level:
              type: string
              enum: [excellent, good, fair, poor]
            recommendation:
              type: string
        field_categories:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
        validation_preview:
          type: object
          properties:
            fields_with_validation:
              type: integer
            total_validation_rules:
              type: integer
            validation_coverage:
              type: number
              minimum: 0.0
              maximum: 1.0

    UIEditableSchema:
      type: object
      properties:
        schema_info:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            description:
              type: string
            source_document:
              type: string
        fields:
          type: object
          additionalProperties:
            type: object
            properties:
              display_name:
                type: string
              type:
                type: string
              required:
                type: boolean
              description:
                type: string
              validation_rules:
                type: array
                items:
                  type: object
              ai_metadata:
                type: object
                properties:
                  confidence:
                    type: number
                  source:
                    type: string
                  requires_review:
                    type: boolean
                  suggested_modifications:
                    type: array
                    items:
                      type: string
        editor_metadata:
          type: object
          properties:
            mode:
              type: string
            ai_assistance_available:
              type: boolean
            confidence_indicators:
              type: boolean
            source_document_available:
              type: boolean

    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object
        ui_message:
          type: string
          description: User-friendly error message for UI display
        suggested_action:
          type: string
          description: Suggested action for user to take
        retry_possible:
          type: boolean
          description: Whether the operation can be retried
      required:
        - error
        - message
        - ui_message